### ISSUE TITLE
Hitting `Esc` in the R window on RStudio in Windows causes spurious send

### ISSUE THREAD

**Issue by alandipert** [rstudio/websocket#12]
I was able to build and run on Windows 10 with R 3.5 after making one minor fix.

The example code also worked, except if I pressed Esc key after executing the code ws$send("hello"), a "received hello" message would be printed to the screen, as if hitting Esc had sent another message.

Debugging with Winston, it seemed adding a cat("here") line to the send method in R stopped the Esc-send to happen.

This was with later version master@d578931 and websocket version master@d8e2aa4

**Comment by wch** [comment]
In RStudio on Windows, when I hit Esc, I get the second send maybe 50% of the time.

In RGui on Windows, I don't get the second send when I press Esc, but I sometimes get this:

```
later: interrupt occurred while executing callback.
```

**Comment by wch** [comment]
I believe that the second send is caused by r-lib/later#61.

**Comment by jcheng5** [comment]
It is indeed r-lib/later#61, see also rstudio/rstudio#3394.
