### ISSUE TITLE
None of the new commits since August work for me.

### ISSUE THREAD

**Issue by ckraner** [rstudio/websocket#21]
I previously had everything working, however I now found two problems (that might compound each other) in the last commits.

1. Just after the "Merge pull request #13 from schloerke/printOutput", server does not run. Returns this every time. Code basically same as original readme where all in one:
 
![image](https://user-images.githubusercontent.com/25021261/44941840-8ccab180-ad6b-11e8-8397-50e22d19310d.png)

2. Since WebsocketClient was renamed to WebSocket, R crashes every time I try to start the client (used new formatting described in new readme)

Information:
Windows 10, i5-6600k, R version 3.4.1

**Comment by jurbanhost** [comment]
> Since WebsocketClient was renamed to WebSocket, R crashes every time I try to start the client (used new formatting described in new readme)

yes, this problem actually for me too

sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

**Comment by jcheng5** [comment]
Sorry to hear this, can you send a reproducible example?
