### ISSUE TITLE
In README, the local server doesn't work

### ISSUE THREAD

**Issue by cawthm** [rstudio/websocket#33]
Specifically, this part: 

"Then to run the WebSocket server, run this in a terminal:"

``` r 
R -e 'source("tmp/websocketServer.R"); httpuv::service(Inf)'
```
<details><summary>Session info</summary>

``` r
devtools::session_info()
#> Session info -------------------------------------------------------------
#>  setting  value                       
#>  version  R version 3.5.1 (2018-07-02)
#>  system   x86_64, darwin15.6.0        
#>  ui       X11                         
#>  language (EN)                        
#>  collate  en_US.UTF-8                 
#>  tz       America/Chicago             
#>  date     2018-10-15
#> Packages -----------------------------------------------------------------
#>  package   * version date       source         
#>  backports   1.1.2   2017-12-13 CRAN (R 3.5.0)
#>  base      * 3.5.1   2018-07-05 local          
#>  compiler    3.5.1   2018-07-05 local          
#>  datasets  * 3.5.1   2018-07-05 local          
#>  devtools    1.13.6  2018-06-27 CRAN (R 3.5.0)
#>  digest      0.6.15  2018-01-28 CRAN (R 3.5.0)
#>  evaluate    0.10.1  2017-06-24 CRAN (R 3.5.0)
#>  graphics  * 3.5.1   2018-07-05 local          
#>  grDevices * 3.5.1   2018-07-05 local          
#>  htmltools   0.3.6   2017-04-28 CRAN (R 3.5.0)
#>  knitr       1.20    2018-02-20 CRAN (R 3.5.0)
#>  magrittr    1.5     2014-11-22 CRAN (R 3.5.0)
#>  memoise     1.1.0   2017-04-21 CRAN (R 3.5.0)
#>  methods   * 3.5.1   2018-07-05 local          
#>  Rcpp        0.12.19 2018-10-01 cran (@0.12.19)
#>  rmarkdown   1.9     2018-03-01 CRAN (R 3.5.0)
#>  rprojroot   1.3-2   2018-01-03 CRAN (R 3.5.0)
#>  stats     * 3.5.1   2018-07-05 local          
#>  stringi     1.2.2   2018-05-02 CRAN (R 3.5.0)
#>  stringr     1.3.1   2018-05-10 CRAN (R 3.5.0)
#>  tools       3.5.1   2018-07-05 local          
#>  utils     * 3.5.1   2018-07-05 local          
#>  withr       2.1.2   2018-03-15 CRAN (R 3.5.0)
#>  yaml        2.1.19  2018-05-01 CRAN (R 3.5.0)
```

</details>

Is there something we should know a priori about the contents of `websocketServer.R`, and/ or is `httpuv::service()` supposed to be doing that work?

Finally and separately; if the person reading this is feeling generous, another question: is any part of the object created an R Connection (maybe a `socketConnection()`)?  I ask because ideally I'd like to pass something to `jsonlite::stream_in()`, which expects a connection.  I suspect this is supposed to happen within the ws$onMessage handler, but I'd sure welcome any advice or further examples.

**Comment by wch** [comment]
That's a mistake in the README. It was written with the implicit assumption that you'd have a local copy of the websocket code, but that's not necessarily the case.

The file it's referencing is in the websocket repo, at https://github.com/rstudio/websocket/blob/master/tmp/websocketServer.R. You can download it and source it, or just copy and paste the code in the R console..

**Comment by wch** [comment]
Oh, also, it is not an R connection object. Offhand I don't know enough about `jsonlite::stream_in()` to give any useful advice.

**Comment by alandipert** [comment]
@cawthm since it looks like Winston addressed this to your satisfaction, I'll go ahead and close it. If you feel the issue remains unresolved, please feel free to re-open.

**Comment by alandipert** [comment]
I edited the README slightly to hopefully make that section clearer: https://github.com/rstudio/websocket/commit/3f27afd2a427b192b225d9ff716fbd7054addc27
