### ISSUE TITLE
CRAN release?

### ISSUE THREAD

**Issue by yihui** [rstudio/websocket#37]
Hi team, I wonder if we have a plan for the CRAN release of this package. I'm asking because the package I'm currently working on may depend on it, and I wish to make a CRAN release of my package before rstudio::conf. Thanks!

**Comment by chapkovski** [comment]
hi, I second this: any news regarding CRAN release? Thanks a lot!

**Comment by alandipert** [comment]
We have submitted to CRAN and I will update this thread when we're live 🚀

**Comment by RLesur** [comment]
I've just seen this package was released on CRAN today. 
Congrats! Many thanks for this work!

**Comment by alandipert** [comment]
@RLesur yup we're on CRAN, thank you for the support!
