### ISSUE TITLE
Rename onClose to onClosed?

### ISSUE THREAD

**Issue by wch** [rstudio/websocket#5]
This is actually about to the websocketClient package: perhaps `onClose` should be renamed to `onClosed`, since it is called *after* the connection is disconnected, from either side?

I feel like `onClose` would be an appropriate name for a callback that's executed when the user calls `$close()`, before the connection is actually closed. I don't hold this opinion strongly, though.

**Comment by alandipert** [comment]
I think `onClose` is good.

If the user is calling `$close()` themselves, then they can also call any other code they want themselves, and so I don't see a reason to add a callback in that case.

Plus, `onclose` is what Javascript calls it, and Javascript is a beautiful and perfectly designed language and runtime.

**Comment by wch** [comment]
Fair enough!
