### ISSUE TITLE
Websocket doesn't connect in batch mode

### ISSUE THREAD

**Issue by vspinu** [rstudio/websocket#50]
When placing the following example into `tmp.R` and running with `R --vanilla --file=tmp.R` the websocket is not connecting:

```R
library(websocket)
ws <- WebSocket$new("ws://echo.websocket.org/",
                    autoConnect = FALSE)
ws$onMessage(function(event) {
  cat("Client got msg:", event$data, "\n")
})
ws$onClose(function(event) {
  cat("Client disconnected\n")
})
ws$onOpen(function(event) {
  cat("Client connected\n")
})
ws$connect()
while(T) {
  cat(".")
  Sys.sleep(1)
}
```
When that code is run directly at interactive session, same issue but the following error is thrown on interrupt after enough time has passed:

```
[2019-04-19 15:24:14] [info] Error getting remote endpoint: asio.system:9 (Bad file descriptor)
[2019-04-19 15:24:14] [info] asio async_shutdown error: asio.system:9 (Bad file descriptor)
[2019-04-19 15:24:14] [error] handle_connect error: Timer Expired
```

My real use case is a bit more involved. I am starting R process from java with `ProcessBuilder`. I can happily interact with the process but cannot start the websocket. In this case `ws$connect()` doesn't produce any output, not even an error.

**Comment by vspinu** [comment]
Ok. This seems to be the limitation of `later` execution model. 

I could make it work with 

```R

while(T) {
  later::run_now()
  Sys.sleep(0.01)
}
```

Is this the recommended way to run the listener in batch mode? Thanks.

**Comment by alandipert** [comment]
@vspinu correct. For some more detail please see https://github.com/rstudio/websocket/issues/40#issuecomment-460763495

**Comment by vspinu** [comment]
Great. Thanks!
