### ISSUE TITLE
Allow changing max_message_size (frame size)

### ISSUE THREAD

**Issue by vspinu** [rstudio/websocket#54]
websocket++ has a limit of 32MB for frame-sizes. This is far too low for data analytic applications. 

Could you please add an option to change that from R level? Thanks.

**Comment by alandipert** [comment]
Thank you for the suggestion, but I can't find where websocket++'s frame size limit is documented. Would you mind pointing me to it?

**Comment by alandipert** [comment]
Oops, nevermind, I missed that you put `max_message_size` in the title. https://docs.websocketpp.org/reference_8config.html

**Comment by alandipert** [comment]
Implementation notes:

* We probably want to surface this as an `options` argument to `WebSocket$new` that takes a named list of websocket++ options, of which `max_message_size` could be one.
* https://docs.websocketpp.org/classwebsocketpp_1_1connection.html#a522286bf83373f87ddebf93b732abffc and other setters on the `connection` class are probably the ones we want to call

**Comment by vspinu** [comment]
I think the only other setting is the timeout. The http_body_size is 32mb by default which is more than plenty for all applications. There are several timeouts setting but I think at R level it better be a single  `timeout` used for all. 

How is ping/pong treated currently? I don't see any support in the code.  It's probably useful to have `pont_timeout_handler` exposed. A topic for another issue I guess.

**Comment by vankesteren** [comment]
I'm running into the maximum message size issue as well! It would be great if we could change this from within R without having to manually chunk our messages.
