### ISSUE TITLE
Build against system websocketpp?

### ISSUE THREAD

**Issue by QuLogic** [rstudio/websocket#59]
Currently, builds use system OpenSSL only, but websocketpp is [available](https://repology.org/project/websocketpp/versions) everywhere except Solaris and Homebrew.

Is there any interest in this? I assume it would have to be optional, but I can write a patch for it.

**Comment by wch** [comment]
Can you explain what the advantage is? I'm not sure I understand.

websocketpp is a header-only library, so there's nothing to link to.
